# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentDash < Formula
  desc "Mission control for AI coding agents - live status, cost and task tracking"
  homepage "https://github.com/gopal-student21/agent-dash"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gopal-student21/agent-dash/releases/download/v0.1.0/agent-dash_0.1.0_darwin_amd64.tar.gz"
      sha256 "85d0f1f5e80d2ac9907f5508d728af1e9722979b90efc931a11b71e764781674"

      def install
        bin.install "agent-dash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gopal-student21/agent-dash/releases/download/v0.1.0/agent-dash_0.1.0_darwin_arm64.tar.gz"
      sha256 "494ca593df97718d6c0df2f78d627b7f06ddae69cbce3975d28e060d51779fba"

      def install
        bin.install "agent-dash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Gopal-student21/agent-dash/releases/download/v0.1.0/agent-dash_0.1.0_linux_amd64.tar.gz"
      sha256 "771c4eed710ece8faa15d8af5fde72e05ac87d7be7b0b22ff8f82a044ccb4d9b"
      def install
        bin.install "agent-dash"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Gopal-student21/agent-dash/releases/download/v0.1.0/agent-dash_0.1.0_linux_arm64.tar.gz"
      sha256 "2e28a52469a5778967eff6ff0c36f7648668a2f60c7bdf4e4c41488eda50dcee"
      def install
        bin.install "agent-dash"
      end
    end
  end
end
