# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devkit < Formula
  desc "DevKit — Universal CLI Dashboard + verification layer for AI-generated code (contract testing, mock server, verify-before-merge)"
  homepage "https://github.com/gopal-student21/devkit"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gopal-student21/devkit/releases/download/v0.9.0/devkit_0.9.0_darwin_amd64.tar.gz"
      sha256 "fb3a81f2bb1ba9810384c5b6c8f67fc145668868eb2c7a34e6ac9cb00ceac557"

      def install
        bin.install "dev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gopal-student21/devkit/releases/download/v0.9.0/devkit_0.9.0_darwin_arm64.tar.gz"
      sha256 "4a714bb319ee12397cc9ff09e968f6cd64151cc476edde55aad300c9a36d9b73"

      def install
        bin.install "dev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Gopal-student21/devkit/releases/download/v0.9.0/devkit_0.9.0_linux_amd64.tar.gz"
      sha256 "f1c3497dcfa89a6803ddd97dcdaa1f5c434e3c170fe5e21ff3f24addf28b88e1"
      def install
        bin.install "dev"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Gopal-student21/devkit/releases/download/v0.9.0/devkit_0.9.0_linux_arm64.tar.gz"
      sha256 "d02a4dc77ecea06b969aac8b54be500b4b306503d6f0000898b410b0624477a7"
      def install
        bin.install "dev"
      end
    end
  end
end
