# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Draft < Formula
  desc "Design website pages with blocks, motion and 3D — export clean HTML/CSS"
  homepage "https://github.com/gopal-student21/draft"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gopal-student21/draft/releases/download/v0.1.0/draft_0.1.0_darwin_amd64.tar.gz"
      sha256 "c13dddf2cc3c15bc23c769d73fa5a9f8d5e30eb580dc81eb4a388900ec5a613f"

      def install
        bin.install "draft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gopal-student21/draft/releases/download/v0.1.0/draft_0.1.0_darwin_arm64.tar.gz"
      sha256 "edfdf56daa3492a199d4fd75a6d0ad4da4a556be03553e5a6396045e568d7586"

      def install
        bin.install "draft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Gopal-student21/draft/releases/download/v0.1.0/draft_0.1.0_linux_amd64.tar.gz"
      sha256 "e0b84d0f1be645d4a9032fa509963371a803192ea9696e92c715d088e08b1d25"
      def install
        bin.install "draft"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Gopal-student21/draft/releases/download/v0.1.0/draft_0.1.0_linux_arm64.tar.gz"
      sha256 "a050ef42e30f62c4fded1185d2eaa4a1247c80a0f6e094666031ce007cb55496"
      def install
        bin.install "draft"
      end
    end
  end
end
