# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synth < Formula
  desc "Local-first AI research synthesis - themes, quotes and exec reports from raw research"
  homepage "https://github.com/gopal-student21/synth"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gopal-student21/synth/releases/download/v0.1.0/synth_0.1.0_darwin_amd64.tar.gz"
      sha256 "d419a21afc516d721fb2a1f080d3a3f831d78c0a10369a2ed306ea317ff582c0"

      def install
        bin.install "synth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gopal-student21/synth/releases/download/v0.1.0/synth_0.1.0_darwin_arm64.tar.gz"
      sha256 "fba3a1008d60ebaf29d171540f7828767950bc8134bc17324b455f54efa7774d"

      def install
        bin.install "synth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Gopal-student21/synth/releases/download/v0.1.0/synth_0.1.0_linux_amd64.tar.gz"
      sha256 "940180c3c2ca4f0f5c6e2bfa6b8e0b7ec81b0dac51c803ec58e82bc1303d0186"
      def install
        bin.install "synth"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Gopal-student21/synth/releases/download/v0.1.0/synth_0.1.0_linux_arm64.tar.gz"
      sha256 "99c79e2ef986a8050a2833100a217bb1cecfcc5a0b3f157397877d651f261063"
      def install
        bin.install "synth"
      end
    end
  end
end
